### PR TITLE
use completableFuture

### PR DESCRIPTION
**Pull request by jtjeferreira**
without this change I need to cast GoogleAnalytics to GoogleAnalyticsImpl to be able to call `postAsync` that returns `CompletableFuture`

### CODE REVIEW

**Comment by jtjeferreira** [comment]
Hi @mikehardy, there is no rush to release this, as I can cast and have an workaround...

**Comment by mikehardy** [comment]
Thanks for the fix - I'm on vacation now so the patience is appreciated but I have time here and there, hopefully I'll check it and release something in the next few days

**Comment by jtjeferreira** [comment]
> Thanks for the fix - I'm on vacation now so the patience is appreciated but I have time here and there, hopefully I'll check it and release something in the next few days

enjoy your vacations then...

**Comment by mikehardy** [comment]
Back from the beach :-), version 2.0.7 should be out on maven repo shortly, or you can fetch it from releases here. Thanks again!

**Pull request merged**
